import { WEBTOON_CANVAS_WIDTH } from '@shared/project-state';

const CANVAS_WIDTH = WEBTOON_CANVAS_WIDTH;
const CANVAS_CONNECTOR_HEIGHT = 56;
const CANVAS_EDGE_BLEND_HEIGHT = 56;
const CANVAS_WORKSPACE_BACKGROUND_COLOR = '#e6edf6';
const DYNAMIC_STYLE_ELEMENT_ID = 'webtoon-panel-studio-dynamic-styles';
const MAX_REFERENCE_IMAGES = 4;

export {
  CANVAS_EDGE_BLEND_HEIGHT,
  CANVAS_CONNECTOR_HEIGHT,
  CANVAS_WORKSPACE_BACKGROUND_COLOR,
  CANVAS_WIDTH,
  DYNAMIC_STYLE_ELEMENT_ID,
  MAX_REFERENCE_IMAGES,
};
